# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

# from tensorflow.keras.models import Sequential
# ann = Sequential()
# ann = tf.keras.models.Sequential()

tf.keras.layers.Dense

# from keras.layers import Dense
# hl = tf.keras.layers.Dense
# hl = Dense(....)

%config Completer.use_jedi = False

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
tf.__version__

'2.0.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])  # Male or Female Column labeled as 0 or 1

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough"
)
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
X = X[:, 1:]
print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

In [12]:
print(X)

[[-0.57873591 -0.57380915 -0.32622142 ...  0.64609167  0.97024255
   0.02188649]
 [-0.57873591  1.74273971 -0.44003595 ... -1.54776799  0.97024255
   0.21653375]
 [-0.57873591 -0.57380915 -1.53679418 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [-0.57873591 -0.57380915  0.60498839 ... -1.54776799  0.97024255
  -1.00864308]
 [ 1.72790383 -0.57380915  1.25683526 ...  0.64609167 -1.03067011
  -0.12523071]
 [-0.57873591 -0.57380915  1.46377078 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

## Training the ANN

### Compiling the ANN
> adam is a optimizer for the weight of the NN and the best is adam which is  a `stochastic gradient descent` method</br>
> lost function: logarithmic loss which for `binary output` would be binary_crossentropy

In [18]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"]) 

### Training the ANN on the Training set

In [19]:
ann.fit(X_train, y_train, batch_size=32, epochs=60)

Train on 8000 samples
Epoch 1/60
8000/8000 [==============================] - 1s 127us/sample - loss: 0.5816 - accuracy: 0.7389
Epoch 2/60
8000/8000 [==============================] - 0s 46us/sample - loss: 0.4955 - accuracy: 0.7995
Epoch 3/60
8000/8000 [==============================] - 0s 49us/sample - loss: 0.4564 - accuracy: 0.8074
Epoch 4/60
8000/8000 [==============================] - 0s 42us/sample - loss: 0.4326 - accuracy: 0.8154
Epoch 5/60
8000/8000 [==============================] - 0s 46us/sample - loss: 0.4155 - accuracy: 0.8200
Epoch 6/60
8000/8000 [==============================] - 0s 49us/sample - loss: 0.3991 - accuracy: 0.8305
Epoch 7/60
8000/8000 [==============================] - 0s 46us/sample - loss: 0.3831 - accuracy: 0.8400
Epoch 8/60
8000/8000 [==============================] - 0s 52us/sample - loss: 0.3713 - accuracy: 0.8470
Epoch 9/60
8000/8000 [==============================] - 0s 49us/sample - loss: 0.3634 - accuracy: 0.8518
Epoch 10/60
8000/8000 [=========

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [20]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1511   84]
 [ 195  210]]


In [22]:
# Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)
(1510+205)/(1510+205+85+200)

0.8605

0.8575